backend:
  name: github
  repo: Hurricane86/EleventyTest
  branch: main
  base_url: https://decap-auth-ojbiyc072-martinos-projects-2d7a3b26.vercel.app
  auth_endpoint: /api/auth
media_folder: "raw_img/uploads"
publish_mode: editorial_workflow
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
     # - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", format: "YYYY-MM-DD"}
      - {label: "tags", name: "tags", widget: "list", default: ["posts"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Cards", name: "cards", widget: "list", field: { name: "card", widget: "card" } }